import { Link } from 'react-router-dom';
import { LandingNav } from '../components/landing/LandingNav';
import { Footer } from '../components/landing/Footer';
import { colors } from '../theme';

const MINT = '#00D4A0';
const CARD_BG = '#111827';
const BORDER = 'rgba(255,255,255,0.06)';

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Clash Display, sans-serif', color: colors.text }}>
        {title}
      </h2>
      <div className="text-sm leading-relaxed" style={{ color: colors.textSecondary }}>
        {children}
      </div>
    </section>
  );
}

function Table({ headers, rows }) {
  return (
    <div className="overflow-x-auto rounded-xl border my-4" style={{ borderColor: BORDER }}>
      <table className="w-full text-sm" style={{ color: colors.text }}>
        <thead>
          <tr style={{ background: 'rgba(255,255,255,0.04)' }}>
            {headers.map((h) => (
              <th key={h} className="text-left py-3 px-4 font-semibold" style={{ color: colors.text }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-t" style={{ borderColor: BORDER }}>
              {row.map((cell, j) => (
                <td key={j} className="py-3 px-4" style={{ color: colors.textSecondary }}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function Privacy() {
  return (
    <div className="min-h-screen" style={{ background: colors.pageBg }}>
      <LandingNav />
      <main className="pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1
            className="text-4xl font-bold tracking-tight mb-2"
            style={{ fontFamily: 'Clash Display, sans-serif', color: colors.text }}
          >
            Privacy Policy
          </h1>
          <p className="text-sm mb-12" style={{ color: colors.textSecondary }}>
            Last updated: 2026. UpiSense is committed to protecting your data under the Digital Personal Data Protection Act 2023.
          </p>

          <Section title="1. Who We Are">
            <p>
              UpiSense is an expense intelligence service. We operate upisense.app and an associated WhatsApp bot.
              Contact: <a href="mailto:privacy@upisense.app" className="font-medium hover:opacity-90" style={{ color: MINT }}>privacy@upisense.app</a>
            </p>
          </Section>

          <Section title="2. What We Collect">
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data you provide</h3>
            <p>Phone number, WhatsApp number, first name, budget amounts, category corrections.</p>
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data generated by use</h3>
            <p>Parsed transaction data (amount, merchant, category, timestamp), merchant memory, anonymised usage data, WhatsApp message metadata.</p>
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data we do NOT collect</h3>
            <p>Bank account numbers, UPI PIN, OTP, raw notification text (deleted in 60 seconds), SMS, contacts, location, camera.</p>
          </Section>

          <Section title="3. How We Use Your Data">
            <Table
              headers={['Purpose', 'Data Used', 'Legal Basis']}
              rows={[
                ['Parse and categorize transactions', 'Notification text (deleted after 60s), structured data', 'Contract performance'],
                ['Display spending dashboard', 'Transaction data, categories', 'Contract performance'],
                ['Send WhatsApp reports and alerts', 'Aggregated data, WhatsApp number', 'Contract performance'],
                ['Improve AI categorization', 'Anonymised merchant names only — never linked to identity', 'Legitimate interest'],
                ['Prevent fraud', 'Phone number, usage patterns', 'Legitimate interest'],
                ['Comply with Indian law', 'As required by court or regulator', 'Legal obligation'],
              ]}
            />
          </Section>

          <Section title="4. AI Processing Disclosure">
            <p>
              When you forward a UPI notification to UpiSense, the text of that message is sent to an AI language model (Google Gemini or Anthropic Claude) for parsing.
              We send only the notification text — your name, phone number, and WhatsApp number are never included in AI API calls.
              The AI provider does not retain your data beyond the API session.
              The raw message text is permanently deleted from our systems within 60 seconds of processing.
            </p>
          </Section>

          <Section title="5. WhatsApp Business Policy">
            <p>
              We use the WhatsApp Business API to communicate with you. We will send: transaction confirmations, weekly spending reports, budget alerts, and onboarding messages.
              We will never send promotional messages unless you explicitly opt in.
              To stop receiving messages at any time, reply <strong>STOP</strong> to any message from UpiSense.
            </p>
          </Section>

          <Section title="6. Data Storage and Security">
            <ul className="list-disc pl-5 space-y-1">
              <li>Data stored in India (primary) and EEA (backup)</li>
              <li>Transit: TLS 1.3</li>
              <li>At rest: AES-256</li>
              <li>Row-level security on database</li>
              <li>Raw message text deleted within 60 seconds</li>
              <li>Security reviews every 6 months</li>
              <li>Breach notification within 72 hours</li>
            </ul>
          </Section>

          <Section title="7. Data Retention">
            <Table
              headers={['Data Type', 'Retention Period', 'Reason']}
              rows={[
                ['Raw notification text', 'Deleted within 60 seconds', 'Minimum necessary'],
                ['Parsed transaction records', 'Duration of account + 90 days after deletion', 'Service delivery'],
                ['Merchant memory', 'Duration of account', 'Personalisation'],
                ['Account data', 'Duration of account + 30 days', 'Orderly closure'],
                ['Anonymised analytics', '24 months rolling', 'Product improvement'],
                ['Payment records', '7 years', 'GST and tax compliance'],
              ]}
            />
          </Section>

          <Section title="8. Third Party Services">
            <Table
              headers={['Provider', 'Purpose', 'Data Shared']}
              rows={[
                ['Meta (WhatsApp Business API)', 'Deliver WhatsApp messages', 'WhatsApp number and message content'],
                ['Google Gemini / Anthropic Claude', 'Parse notification text', 'Anonymised notification text only'],
                ['Supabase', 'Database hosting', 'All structured user data'],
                ['Razorpay', 'Payment processing', 'Subscription status only — no card details'],
              ]}
            />
            <p className="mt-2">
              <a href="https://razorpay.com/privacy/" target="_blank" rel="noopener noreferrer" className="font-medium hover:opacity-90" style={{ color: MINT }}>Razorpay&apos;s privacy policy</a>
              {' · '}
              <a href="https://supabase.com/dpa" target="_blank" rel="noopener noreferrer" className="font-medium hover:opacity-90" style={{ color: MINT }}>Supabase&apos;s data processing agreement</a>
            </p>
          </Section>

          <Section title="9. Your Rights (DPDP Act 2023)">
            <ul className="space-y-3">
              <li><strong style={{ color: colors.text }}>Right to access</strong> — email privacy@upisense.app</li>
              <li><strong style={{ color: colors.text }}>Right to correction</strong> — update in dashboard or email us</li>
              <li><strong style={{ color: colors.text }}>Right to erasure</strong> — use Delete Account in Settings or email us, deleted within 30 days</li>
              <li><strong style={{ color: colors.text }}>Right to grievance redressal</strong> — contact dpo@upisense.app</li>
              <li><strong style={{ color: colors.text }}>Right to nominate</strong> — contact privacy@upisense.app</li>
            </ul>
            <p className="mt-3">We respond to all requests within 30 days.</p>
          </Section>

          <Section title="10. Cookie Policy">
            <p>
              UpiSense uses only essential session cookies required for login and authentication. We do not use advertising cookies, tracking cookies, or third-party analytics cookies.
              No cookie consent banner is required as we use only strictly necessary cookies.
            </p>
          </Section>

          <Section title="11. Children's Privacy">
            <p>
              UpiSense is not intended for users under 18. If you believe a minor has registered, email <a href="mailto:privacy@upisense.app" className="font-medium hover:opacity-90" style={{ color: MINT }}>privacy@upisense.app</a>.
            </p>
          </Section>

          <Section title="12. Changes to This Policy">
            <p>
              We notify users of material changes via WhatsApp and dashboard notice at least 30 days before changes take effect.
            </p>
          </Section>

          <Section title="13. Grievance Officer">
            <div
              className="rounded-xl border-2 p-6 my-4"
              style={{ background: 'rgba(0,212,160,0.06)', borderColor: MINT }}
            >
              <p className="font-semibold mb-2" style={{ color: colors.text }}>Data Protection Officer / Grievance Officer</p>
              <p style={{ color: colors.textSecondary }}>
                Name: <span className="px-1.5 py-0.5 rounded font-medium" style={{ background: '#FEF08A', color: '#000' }}>[FILL IN BEFORE LAUNCH: Your Name]</span>
              </p>
              <p style={{ color: colors.textSecondary }}>Email: dpo@upisense.app</p>
              <p style={{ color: colors.textSecondary }}>
                Address: <span className="px-1.5 py-0.5 rounded font-medium" style={{ background: '#FEF08A', color: '#000' }}>[FILL IN BEFORE LAUNCH: Your Address]</span>
              </p>
              <p className="mt-3 text-sm" style={{ color: colors.textSecondary }}>
                Complaints will be acknowledged within 48 hours and resolved within 30 days as required by the Information Technology Act 2000 and the Digital Personal Data Protection Act 2023.
              </p>
            </div>
          </Section>

          <p className="mt-12 text-sm" style={{ color: colors.textSecondary }}>
            <Link to="/terms" className="font-medium hover:opacity-90" style={{ color: MINT }}>Terms of Service</Link>
            {' · '}
            <Link to="/contact" className="font-medium hover:opacity-90" style={{ color: MINT }}>Contact</Link>
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
