import { Link } from 'react-router-dom';
import { LandingNav } from '../components/landing/LandingNav';
import { Footer } from '../components/landing/Footer';
import { colors } from '../theme';

const MINT = '#00D4A0';
const CARD_BG = '#111827';
const BORDER = 'rgba(255,255,255,0.06)';

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold mb-4" style={{ fontFamily: 'Clash Display, sans-serif', color: colors.text }}>
        {title}
      </h2>
      <div className="text-sm leading-relaxed" style={{ color: colors.textSecondary }}>
        {children}
      </div>
    </section>
  );
}

function Table({ headers, rows }) {
  return (
    <div className="overflow-x-auto rounded-xl border my-4" style={{ borderColor: BORDER }}>
      <table className="w-full text-sm" style={{ color: colors.text }}>
        <thead>
          <tr style={{ background: 'rgba(255,255,255,0.04)' }}>
            {headers.map((h) => (
              <th key={h} className="text-left py-3 px-4 font-semibold" style={{ color: colors.text }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-t" style={{ borderColor: BORDER }}>
              {row.map((cell, j) => (
                <td key={j} className="py-3 px-4" style={{ color: colors.textSecondary }}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function Privacy() {
  return (
    <div className="min-h-screen" style={{ background: colors.pageBg }}>
      <LandingNav />
      <main className="pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-3xl mx-auto">
          <h1
            className="text-4xl font-bold tracking-tight mb-2"
            style={{ fontFamily: 'Clash Display, sans-serif', color: colors.text }}
          >
            Privacy Policy
          </h1>
          <p className="text-sm mb-12" style={{ color: colors.textSecondary }}>
            Last updated: 1 April 2026. UpiSense is committed to protecting your data under the Digital Personal Data Protection Act 2023.
          </p>

          <Section title="1. Who We Are">
            <p>
              UpiSense is an expense intelligence service. We operate upisense.app and an associated WhatsApp bot.
              UpiSense is operated by Kushal Mehta, a sole proprietor.
            </p>
            <p className="mt-2">
              Contact: <a href="mailto:privacy@upisense.app" className="font-medium hover:opacity-90" style={{ color: MINT }}>privacy@upisense.app</a>
            </p>
          </Section>

          <Section title="2. What We Collect">
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data you provide</h3>
            <p>Phone number, WhatsApp number, first name, budget amounts, category corrections.</p>
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data generated by use</h3>
            <p>
              Parsed transaction data (amount, merchant, category, timestamp), merchant/category preferences for your account, and operational
              error logs that do not include full message content in production. We do not run third-party advertising or product analytics on
              the app.
            </p>
            <h3 className="font-medium mt-2 mb-1" style={{ color: colors.text }}>Data we do NOT collect</h3>
            <p>
              UPI PIN, OTP, or your contacts book. We do not store complete raw bank/SMS notification text as a field in our database; we save
              structured fields after parsing. We do not access your SMS inbox or device camera directly (if you send a receipt image on WhatsApp,
              that image is processed as described in the AI section below).
            </p>
          </Section>

          <Section title="3. How We Use Your Data">
            <Table
              headers={['Purpose', 'Data Used', 'Legal Basis']}
              rows={[
                ['Parse and categorize transactions', 'Message or forwarded text for parsing (see section 4), then structured fields we store', 'Contract performance'],
                ['Display spending dashboard', 'Transaction data, categories', 'Contract performance'],
                ['Send WhatsApp reports and alerts', 'Aggregated data, WhatsApp number', 'Contract performance'],
                ['Personalise categories', 'Merchant names and your category choices stored for your account', 'Contract performance'],
                ['Prevent abuse', 'Phone number, basic usage signals', 'Legitimate interest'],
                ['Comply with Indian law', 'As required by court or regulator', 'Legal obligation'],
              ]}
            />
          </Section>

          <Section title="4. AI Processing Disclosure">
            <p className="mb-3">
              UpiSense uses <strong>Google Gemini</strong> (Google Generative AI) for: (1) parsing text when rule-based parsing cannot read a message,
              (2) interpreting natural-language commands on WhatsApp, and (3) reading receipt or screenshot images you send on WhatsApp to extract
              amount and merchant. We do not currently call other model providers in production; if we add any, we will update this policy.
            </p>
            <p className="mb-3">
              For text parsing, we send the <strong>message content</strong> to Google&apos;s API so it can return structured fields. We do not add
              your account name, phone number, or WhatsApp ID as separate fields in that request; however, <strong>those details may still appear inside
              the message</strong> if you or your bank included them in the forwarded text. Receipt images are sent to Google for vision parsing
              only for that request.
            </p>
            <p className="mb-3">
              Google&apos;s retention and subprocessors are governed by{' '}
              <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="font-medium hover:opacity-90" style={{ color: MINT }}>Google&apos;s Gemini API terms</a>
              {' '}and privacy documentation — review them for details beyond our control.
            </p>
            <p>
              <strong>What we store:</strong> We do not persist the full raw notification or full chat message as a single stored &quot;raw text&quot;
              column in our database. We store the <strong>parsed result</strong> (e.g. amount, merchant label, category). Message text may exist
              briefly in server memory while handling a request. In production we avoid writing full UPI/bank message content to application logs.
            </p>
          </Section>

          <Section title="5. WhatsApp Business Policy">
            <p>
              We use the WhatsApp Business API to communicate with you. We will send: transaction confirmations, weekly spending reports, budget alerts, and onboarding messages.
              We will never send promotional messages unless you explicitly opt in.
              To stop receiving messages at any time, reply <strong>STOP</strong> to any message from UpiSense.
            </p>
          </Section>

          <Section title="6. Data Storage and Security">
            <ul className="list-disc pl-5 space-y-1">
              <li>Data stored in India on Supabase infrastructure.</li>
              <li>Transit: TLS (HTTPS) between your browser, our API, and providers.</li>
              <li>At rest: encryption provided by our database host (standard cloud storage encryption).</li>
              <li>Access control: row-level security and authenticated APIs so each user&apos;s data is isolated.</li>
              <li>We do not store complete raw bank/UPI notification text as a database field; see section 4.</li>
              <li>We review security configuration regularly and aim to notify affected users of significant breaches without undue delay.</li>
            </ul>
          </Section>

          <Section title="7. Data Retention">
            <Table
              headers={['Data Type', 'Retention Period', 'Reason']}
              rows={[
                ['Full raw notification text', 'Not kept as a dedicated database record; see section 4', 'Minimum necessary'],
                ['Parsed transaction records', 'Duration of account + 90 days after deletion', 'Service delivery'],
                ['Merchant memory', 'Duration of account', 'Personalisation'],
                ['Account data', 'Duration of account + 30 days after closure request', 'Orderly closure'],
                ['Operational / error logs', 'Short retention on our host; no full message content in production logs', 'Reliability and security'],
                ['Payment records (when paid plans apply)', '7 years', 'GST and tax compliance — applicable when paid plans are introduced'],
              ]}
            />
          </Section>

          <Section title="8. Third Party Services">
            <Table
              headers={['Provider', 'Purpose', 'Data Shared']}
              rows={[
                ['Meta (WhatsApp Business API)', 'Deliver WhatsApp messages', 'WhatsApp number and message content you send to our business number'],
                ['Google (Gemini API)', 'Parse text and receipt images', 'Message or image content required for that parse; see section 4'],
                ['Supabase', 'Database and auth hosting', 'Structured account and transaction data'],
                ['Razorpay (when paid plans apply)', 'Payment processing', 'Subscription status only — no card details (applicable when paid plans are introduced)'],
              ]}
            />
            <p className="mt-2">
              <a href="https://supabase.com/dpa" target="_blank" rel="noopener noreferrer" className="font-medium hover:opacity-90" style={{ color: MINT }}>Supabase&apos;s data processing agreement</a>
              {' · '}
              <a href="https://razorpay.com/privacy/" target="_blank" rel="noopener noreferrer" className="font-medium hover:opacity-90" style={{ color: MINT }}>Razorpay&apos;s privacy policy</a>
              <span className="text-xs ml-1" style={{ color: colors.textSecondary }}>(applicable when paid plans are introduced)</span>
            </p>
          </Section>

          <Section title="9. Your Rights (DPDP Act 2023)">
            <ul className="space-y-3">
              <li><strong style={{ color: colors.text }}>Right to access</strong> — email privacy@upisense.app</li>
              <li><strong style={{ color: colors.text }}>Right to correction</strong> — update in dashboard or email us</li>
              <li><strong style={{ color: colors.text }}>Right to erasure</strong> — use Delete Account in Settings or email us, deleted within 30 days</li>
              <li><strong style={{ color: colors.text }}>Right to grievance redressal</strong> — contact dpo@upisense.app</li>
              <li><strong style={{ color: colors.text }}>Right to nominate</strong> — contact privacy@upisense.app</li>
            </ul>
            <p className="mt-3">We respond to all requests within 30 days.</p>
          </Section>

          <Section title="10. Cookies and browser storage">
            <p>
              We store your session token in the browser&apos;s <strong>local storage or session storage</strong> (depending on whether you choose
              &quot;Remember me&quot;), so you stay logged in. We do not use advertising cookies, third-party marketing trackers, or third-party
              analytics cookies on the web app. Essential or similar storage may also be used by our hosting and auth providers as part of delivering
              the service. If we introduce non-essential cookies, we will update this section and obtain consent where required.
            </p>
          </Section>

          <Section title="11. Children's Privacy">
            <p>
              UpiSense is not intended for users under 18. If you believe a minor has registered, email <a href="mailto:privacy@upisense.app" className="font-medium hover:opacity-90" style={{ color: MINT }}>privacy@upisense.app</a>.
            </p>
          </Section>

          <Section title="12. Changes to This Policy">
            <p>
              We notify users of material changes via WhatsApp and dashboard notice at least 30 days before changes take effect.
            </p>
          </Section>

          <Section title="13. Grievance Officer">
            <div
              className="rounded-xl border-2 p-6 my-4"
              style={{ background: 'rgba(0,212,160,0.06)', borderColor: MINT }}
            >
              <p className="font-semibold mb-2" style={{ color: colors.text }}>Data Protection Officer / Grievance Officer</p>
              <p style={{ color: colors.textSecondary }}>
                Name: <span style={{ color: colors.text }}>Kushal Mehta</span>
              </p>
              <p style={{ color: colors.textSecondary }}>Email: dpo@upisense.app</p>
              <p style={{ color: colors.textSecondary }}>
                Address: <span style={{ color: colors.text }}>Mumbai, India</span>
              </p>
              <p className="mt-3 text-sm" style={{ color: colors.textSecondary }}>
                Complaints will be acknowledged within 48 hours and resolved within 30 days as required by the Information Technology Act 2000 and the Digital Personal Data Protection Act 2023.
              </p>
            </div>
          </Section>

          <p className="mt-12 text-sm" style={{ color: colors.textSecondary }}>
            <Link to="/terms" className="font-medium hover:opacity-90" style={{ color: MINT }}>Terms of Service</Link>
            {' · '}
            <Link to="/contact" className="font-medium hover:opacity-90" style={{ color: MINT }}>Contact</Link>
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
